### ISSUE TITLE
Not clear how to return to main calendar after searching for item in serch bar.

### ISSUE THREAD

**Issue by ddluc-qa** [ddluc/harvest-calendar#5]
After you search for an item in the search bar it is not immediately clear how you return to the main calendar. After a series of trial and error  clicks I realized that you need to click on the "x" in the search box to clear the search results. The "x" is visible when you initially do the search but if you choose to view this item in a different season the "x" disappears from the search box. It is not until you re-click in the search box that the "x" re-appears. Then it only resets the calendar after you choose the "x" option and then click on another season

![](https://user-images.githubusercontent.com/59975971/75069445-0b5a6800-54a6-11ea-817a-d51255f73680.png)

**Comment by ddluc** [comment]
Note: This is only happening on Windows browsers. @ddluc-qa Can you provide a list of browsers affected by this issue on Windows OS?

**Comment by ddluc-qa** [comment]
![Search Bar issue](https://user-images.githubusercontent.com/59975971/75069445-0b5a6800-54a6-11ea-817a-d51255f73680.png)
